### ISSUE TITLE
Package guzzle/parser is abandoned

### ISSUE THREAD

**Issue by tomzx** [reactphp/http#24]
When installing `react/http` through composer, the following error is issued:

Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.

The error can be ignored, but it would probably be wise to update that dependency.

**Comment by SamMousa** [comment]
Bump

**Comment by WyriHaximus** [comment]
We're aware of it and for now it's just a warning and the package will still be installed. Just updating that dependency to guzzle/guzzle is also tricky since that requires ext-curl and we don't have that dependency so it doesn't make sense to depend on that. So we're still working on coming up with a good alternative.

**Comment by SamMousa** [comment]
That's just a dev-dependency, (not sure if that makes a difference)

**Comment by WyriHaximus** [comment]
It's not a dev-dependency it's a normal dependency from [guzzle/guzzle](https://packagist.org/packages/guzzle/guzzle).
