### ISSUE TITLE
Server arguments are potentially ambiguous

### ISSUE THREAD

**Issue by kelunik** [reactphp/http#303]
The following code also seems problematic: `new Server([$foobar, "handleRequest"]);` It could either be a single callable with the method `handleRequest` on `$foobar` or an array with `$foobar` implementing `__invoke()` and `handleRequest` being an ordinary function implementing a middleware.

Without looking at the code, I can't tell which one it will be.

**Comment by clue** [comment]
Thanks for reporting! Both `Server` and `StreamingServer` will first check to see if this is a `callable`. Accordingly, this will be invoked as `$foobar->handleRequest($request)`. I agree that we may want to add some documentation to describe this :+1:

**Comment by kelunik** [comment]
A potential way to mitigate this is using `new Server([[$foobar, "__invoke"], "handleRequest"]);`. Another way would be introducing a `Middleware` and `RequestHandler` interface.

**Comment by clue** [comment]
It's my understanding that this needs documentation instead of "mitigation" (http://www.dictionary.com/browse/mitigate).

Accordingly, if you're indeed in the situation where you have a class that implements  both the `__invoke()` and `handleRequest()` methods *and* you have a global `handleRequest()` function that you actually want to execute instead, then you would have to use the array definition as you've suggested above.

I feel like I'm stating the obvious here, but at this point I'm *not convinced* that implementing two interfaces to avoid this particular case would be beneficial for the majority of our users.

> mitigate
>verb (used with object), mitigated, mitigating.
> 1. to lessen in force or intensity, as wrath, grief, harshness, or pain; moderate.
> 2. to make less severe: to mitigate a punishment.
> 3. to make (a person, one's state of mind, disposition, etc.) milder or more gentle; mollify; appease.
verb (used without object), mitigated, mitigating.
> 4. to become milder; lessen in severity.

**Comment by kelunik** [comment]
I'm not suggesting that these interface should be added just because of this issue. Rather, introducing these solves this issue as well.

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. Please come back with more details if this problem persists and we can reopen this :+1:
