### ISSUE TITLE
The psr/http-message v2 is not supported

### ISSUE THREAD

**Issue by SergeC** [reactphp/http#512]
The psr/http-message v2 is not supported. Please add support,
```
Downgrading psr/http-message (2.0 => 1.1)
```

**Comment by SimonFrings** [comment]
@SergeC I opened a ticket to add support for psr/http-message v2 in #513. This ticket should include all necessary information for the v2 upgrade. As also mentioned in said ticket, we first need to remove our dependency on `ringcentral/psr7`, otherwise we can't be compatible with  psr/http-message v2.

Additionally, I think this ticket here is more of a feature request instead a bug. We recommend opening bug tickets only when you can provide evidence of something being broken, just as a friendly reminder for future tickets :)

I believe this should answer everything in here, so I will close this ticket. Further discussion will happen in #513.
