### ISSUE TITLE
Support chunked transfer encoding

### ISSUE THREAD

**Issue by clue** [reactphp/http#96]
See https://tools.ietf.org/html/rfc7230#section-3.3.1 and https://tools.ietf.org/html/rfc7230#section-3.3

**Comment by WyriHaximus** [comment]
FYI we support it from our side to the client but not the other way around yet: https://github.com/reactphp/http/blob/master/src/Response.php#L99-L105

**Comment by clue** [comment]
Thanks for linking to this, FWIW, this has been implemented in the HttpClient component via https://github.com/reactphp/http-client/pull/58

**Comment by clue** [comment]
I hear @legionth may be working on this feature currently, perhaps he can chime in here? :grinning:

**Comment by legionth** [comment]
Yes, I'm currently working on this. Because the client and server component are currently seperated (and I think this won't change in the next days), I would consider to put a chunked encoder and decoder into this package. Even if this would lead to a duplication.

I will check if this https://github.com/reactphp/http-client/pull/58 or this https://github.com/legionth/php-http-server-react/blob/master/src/ChunkedDecoder.php is better to use in my current work.
